# ==============================================================
# DBT PROJECT CONFIGURATION
# ==============================================================
name: 'Astrafy'
version: '1.0.0'

profile: 'Astrafy'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Astrafy:
    +materialized: table
    staging:
      +schema: Astrafy_staging
      +materialized: view
    marts:
      +schema: Astrafy_marts
      +materialized: table
