version: 2

models:
  - name: ex_1_total_orders
    description: "Total number of unique orders placed in 2023."
  - name: ex_2_orders_per_month
    description: "Monthly order volume for 2023."
  - name: ex_3_avg_products_per_order
    description: "Average number of products per order for each month in 2023."
  - name: ex_4_orders_with_qty
    description: "Orders for 2022–2023 with total quantity of products per order."
  - name: ex_5_order_segmentation
    description: "Customer segmentation: New / Returning / VIP for 2023."
  - name: ex_6_orders_2023_with_segmentation
    description: "Final 2023 orders table enriched with segmentation."
