version: 2

models:
  - name: ex_1_total_orders
    description: "Total number of unique orders placed in 2023."

  - name: ex_2_orders_per_month
    description: "Monthly order volume for 2023."

  - name: ex_3_avg_products_per_order
    description: "Average number of distinct products per order per month in 2023."

  - name: ex_4_orders_with_qty
    description: "Orders for 2022–2023 with the total quantity of products in each order."
    columns:
      - name: qty_product
        description: "Total quantity of products per order."

  - name: ex_5_order_segmentation
    description: "Segmentation of 2023 orders based on past 12-month purchase behavior."
    columns:
      - name: order_segment
        description: "Customer segment: New, Returning, or VIP."

  - name: ex_6_orders_2023_with_segmentation
    description: "2023 orders enriched with customer segmentation."
    columns:
      - name: order_segment
        description: "Customer segment: New, Returning, or VIP."
